2024-05-15 21:34:25 [scrapy.core.engine] ERROR: Scraper close failure
Traceback (most recent call last):
  File "E:\Softwares\Anaconda\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "D:\2024Spring\DLsite-Analysis\MainSite_Crawler\MainSite_CrawlerV2.0\MainSite_Crawler\pipelines.py", line 48, in close_spider
    all_ids.append({"ID" : key, "verified": value['verified'], "controversial": value['controversial']})
TypeError: 'set' object is not subscriptable
